version: '3.9'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  celery-worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: celery-worker
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=${BROKER_URL}
    depends_on:
      - app
      - redis
    volumes:
      - ..:/app/
    command: celery -A main.celery worker --loglevel=info


  flower:
    image: "mher/flower:latest"
    container_name: flower
    ports:
      - "5555:5555"
    depends_on:
      - app
      - celery-worker
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=${BROKER_URL}
      - FLOWER_PORT=5555


volumes:
  redis_data: